default:
  name: "tauhtauh"
  triggerselections: 
    HLT_DoubleMediumChargedIsoPFTauHPS40_Trk1_eta2p1: true
  objselections:
    GenPart: null
    Electron: 
      cbtightid: 1
      mvaisoid: 0.8
      pt: 25
      eta: 2.1
      dxy: 0.045
      dz: 0.2
      count: 0
    Muon: 
      pt: 20
      eta: 2.1
      dxy: 0.045
      dz: 0.2
      looseid: true
      isoid: 1
      count: 0
    Tau:
      pt: 40
      eta: 2.3
      idvsjet: 5
      idvsmu: 1
      idvse: 2
      dz: 0.2
      count: 2
      OS: true
    Jet:
      pt: 20
      eta: 2.4
      btag: 0.3196	
      count: 2
    FatJet:
      mass: 40
      count: 1
  outputs:
    Tau:
      pt: Tau_pt
      eta: Tau_eta
      phi: Tau_phi
      mass: Tau_mass
      dxy: Tau_dxy
      dz: Tau_dz
      charge: Tau_charge
      idvsjet: Tau_idDeepTau2018v2p5VSjet
      idvsmu: Tau_idDeepTau2017v2p1VSmu
      idvse: Tau_idDeepTau2017v2p1VSe
    Electron:
      pt: Electron_pt
      eta: Electron_eta
      phi: Electron_phi
      mass: Electron_mass
      dxy: Electron_dxy
      dz: Electron_dz
      cbtightid: Electron_cutBased
      mvaisoid: Electron_mvaIso
      charge: Electron_charge
    Muon:
      pt: Muon_pt
      eta: Muon_eta
      phi: Muon_phi
      mass: Muon_mass
      dxy: Muon_dxy
      dz: Muon_dz
      looseid: Muon_looseId
      isoid: Muon_pfIsoId
      cbtightid: Muon_tightId
      charge: Muon_charge
    Jet:
      pt: Jet_pt
      eta: Jet_eta
      phi: Jet_phi
      mass: Jet_mass
      btag: Jet_btagDeepFlavB
      deepJetCvsB: Jet_btagDeepFlavCvB
      jetID: Jet_jetId
    FatJet:
      pt: FatJet_pt
      eta: FatJet_eta
      phi: FatJet_phi
      mass: FatJet_mass
      jetID: FatJet_jetId
    GenPart:
      pt: GenPart_pt
      eta: GenPart_eta
      phi: GenPart_phi
      mass: GenPart_mass
      pdgid: GenPart_pdgId
      motherid: GenPart_genPartIdxMother



          
          
