[LOCAL]
LOCAL_TEST = true
SINGLE_PATH = "/Users/yuntongzhou/Desktop/Dihiggszztt/sample1.root"
PROCESS_NAME = "DYJets"
OUTPUTDIR_PATH = "@format {env[OUTPUTPATH]}"
TRANSFER = false

[LPCLOCAL]
PROCESS_NAME = "SingleH"
TREE_NAME = "Events"
CONDORPATH = "/store/user/joyzhou/output"
SCRATCHPATH = "/uscmst1b_scratch/lpc1/3DayLifetime/joyzhou"
INPUTFILE_PATH = "@format src/data/preprocessed/{this.PROCESS_NAME}.json"
OUTPUTDIR_PATH = "@format {this.SCRATCHPATH}/output/{this.PROCESS_NAME}"
TRANSFER = true
TRANSFER_PATH = "@format {this.CONDORPATH}/{this.PROCESS_NAME}"
COPY_LOCAL = true
STEP_SIZE = '400MB'
COPY_DIR = "@format {this.SCRATCHPATH}/temp"

[LPCCONDOR]
PROCESS_NAME = "@format {env[PROCESS_NAME]}"
TREE_NAME = "Events"
SEL_NAME = 'skim'
CONDORPATH = "/store/user/joyzhou/skim"
# INPUTFILE_PATH = "@format /store/user/joyzhou/hadded/{this.PROCESS_NAME}"
INPUTFILE_PATH = "@format src/data/preprocessed/{this.PROCESS_NAME}.json"
OUTPUTDIR_PATH = "@format outputs/{this.PROCESS_NAME}"
TRANSFER = true
TRANSFER_PATH = "@format {this.CONDORPATH}/{this.PROCESS_NAME}"
COPY_LOCAL = true
COPY_DIR = "temp"
STEP_SIZE = '180MB'
RESUME = true
DSINDX = ['TTto2L2N']
FINDX = 64

[LPCJUPYTER]
PROCESS_NAME = "ggF"
TREE_NAME = "Events"
SEL_NAME = 'skim'
CONDORPATH = "/store/user/joyzhou/output"
INPUTFILE_PATH = "@format src/data/preprocessed/{this.PROCESS_NAME}.json"
OUTPUTDIR_PATH = "/uscms/home/joyzhou/nobackup/tests"
TRANSFER = true
TRANSFER_PATH = "@format {this.CONDORPATH}/tests"
COPY_LOCAL = true
COPY_DIR = "/uscms/home/joyzhou/nobackup/temp"
STEP_SIZE = false
RESUME = false
DSINDX = 0
FINDX = 0
